
tasks:
  - init: mvn install -DskipTests=false

# and commit this file to your remote git repository to share the goodness with others.
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - revaturepro.revature-labs

    - redhat.java

